"use client";

import Link from "next/link";
import {FormEvent,useState} from "react";
import {CheckCircle2} from "lucide-react";
import {Logo} from "./ui";

export function ForgotPasswordForm(){const [busy,setBusy]=useState(false),[error,setError]=useState(""),[sent,setSent]=useState(false),[resetToken,setResetToken]=useState<string|null>(null);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");try{const payload=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/backend/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.detail);setResetToken(data.reset_token);setSent(true)}catch(caught){setError(caught instanceof Error?caught.message:"Something went wrong.")}finally{setBusy(false)}}return <AuthFrame title="Reset your password" subtitle="Enter the email address connected to your Fuuud account.">{sent?<div className="card p-6 text-center"><CheckCircle2 className="mx-auto text-green-600" size={34}/><h2 className="mt-3 font-black">Check your reset instructions</h2><p className="muted mt-2 text-sm">If that email belongs to an account, reset instructions are ready.</p>{resetToken&&<Link className="btn btn-primary mt-5 w-full" href={`/reset-password?token=${encodeURIComponent(resetToken)}`}>Continue to reset password</Link>}<Link className="btn btn-outline mt-3 w-full" href="/login">Back to login</Link></div>:<form onSubmit={submit} className="card mt-7 space-y-4 p-6"><label className="block text-sm font-bold">Email address<input required name="email" className="field mt-2" type="email" autoComplete="email" placeholder="you@example.com"/></label>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}<button disabled={busy} className="btn btn-primary w-full">{busy?"Please wait...":"Send reset instructions"}</button><Link className="btn btn-outline w-full" href="/login">Back to login</Link></form>}</AuthFrame>}

export function ResetPasswordForm({token}:{token:string}){const [busy,setBusy]=useState(false),[error,setError]=useState(""),[complete,setComplete]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const payload=Object.fromEntries(new FormData(event.currentTarget));if(payload.password!==payload.confirm_password){setError("Passwords do not match.");setBusy(false);return}try{const response=await fetch("/api/backend/auth/reset-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password:payload.password})});const data=await response.json();if(!response.ok)throw new Error(data.detail);setComplete(true)}catch(caught){setError(caught instanceof Error?caught.message:"Something went wrong.")}finally{setBusy(false)}}return <AuthFrame title="Choose a new password" subtitle="Use at least eight characters and keep it private.">{complete?<div className="card p-6 text-center"><CheckCircle2 className="mx-auto text-green-600" size={34}/><h2 className="mt-3 font-black">Password updated</h2><p className="muted mt-2 text-sm">You can now sign in with your new password.</p><Link className="btn btn-primary mt-5 w-full" href="/login">Continue to login</Link></div>:token?<form onSubmit={submit} className="card mt-7 space-y-4 p-6"><label className="block text-sm font-bold">New password<input required minLength={8} maxLength={128} name="password" className="field mt-2" type="password" autoComplete="new-password"/></label><label className="block text-sm font-bold">Confirm new password<input required minLength={8} maxLength={128} name="confirm_password" className="field mt-2" type="password" autoComplete="new-password"/></label>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}<button disabled={busy} className="btn btn-primary w-full">{busy?"Updating...":"Update password"}</button></form>:<div className="card p-6 text-center"><h2 className="font-black">Reset link missing</h2><p className="muted mt-2 text-sm">Request a new password reset link to continue.</p><Link className="btn btn-primary mt-5 w-full" href="/forgot-password">Request a reset link</Link></div>}</AuthFrame>}

function AuthFrame({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="page max-w-md md:!ml-auto"><div className="text-center"><Logo/><h1 className="mt-8 text-3xl font-black">{title}</h1><p className="muted mt-2">{subtitle}</p></div><div className="mt-7">{children}</div></div>}
