import Link from "next/link";import {BadgeCheck,MapPin,Star,Search,ChevronRight,Calendar,Clock,Phone,Navigation,ArrowLeft} from "lucide-react";import type {Doctor,Hospital,Prescription} from "@/types";
// Three connected u-shaped supports echo the name and place a person at the centre.
export function Logo(){return <Link href="/" className="brand-logo" aria-label="Fuuud home"><span className="brand-mark" aria-hidden="true"><svg width="40" height="40" viewBox="0 0 40 40" fill="none"><path d="M4 11V24C4 33.333 14 33.333 14 24V18M14 24C14 33.333 26 33.333 26 24V18M26 24C26 33.333 36 33.333 36 24V11" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round"/><circle cx="20" cy="11" r="3.5" fill="currentColor"/></svg></span><span>Fuuud</span><span className="sr-only"> ? Care, closer.</span></Link>}
export function PageHeader({title,subtitle,back}:{title:string;subtitle?:string;back?:string}){return <header className="app-page-header"><div className="flex items-center gap-2.5">{back&&<Link href={back} className="app-back" aria-label="Go back"><ArrowLeft size={18}/></Link>}<h1 className="app-page-title">{title}</h1></div>{subtitle&&<p className="app-page-subtitle">{subtitle}</p>}</header>}
export function SearchInput({placeholder="Search",defaultValue}:{placeholder?:string;defaultValue?:string}){return <label className="relative block"><span className="sr-only">{placeholder}</span><Search className="absolute left-4 top-3.5 text-slate-400" size={19}/><input defaultValue={defaultValue} className="field pl-11" placeholder={placeholder}/></label>}
export function VerifiedBadge(){return <span className="pill bg-green-50 text-green-700"><BadgeCheck size={14}/>Verified</span>}
export function StatusBadge({children,tone="green"}:{children:React.ReactNode;tone?:"green"|"red"|"amber"}){const c=tone==="red"?"bg-red-50 text-red-700":tone==="amber"?"bg-amber-50 text-amber-700":"bg-green-50 text-green-700";return <span className={`pill ${c}`}>{children}</span>}
export function Avatar({initials,large=false}:{initials:string;large?:boolean}){return <div className={`${large?"h-24 w-24 text-2xl":"h-14 w-14 text-base"} shrink-0 rounded-2xl bg-green-100 text-green-800 grid place-items-center font-black`} aria-hidden>{initials}</div>}
export function DoctorCard({doctor}:{doctor:Doctor}){return <article className="card p-5"><div className="flex gap-4"><Avatar initials={doctor.initials}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-extrabold">{doctor.name}</h2>{doctor.verified&&<BadgeCheck className="text-green-600" size={17}/>}</div><p className="text-sm text-green-700 font-semibold">{doctor.specialty}</p><p className="muted text-sm">{doctor.title}</p></div></div><div className="grid grid-cols-2 gap-2 mt-4 text-sm"><span className="flex gap-1"><MapPin size={16}/>{doctor.location}</span><span className="flex gap-1"><Star size={16} className="text-amber-500"/> {doctor.rating} · {doctor.experience} yrs</span><span className="font-bold">₦{doctor.fee.toLocaleString()}</span><span className="text-green-700">Next: {doctor.next}</span></div><div className="flex gap-2 mt-5"><Link className="btn btn-outline flex-1" href={`/doctors/${doctor.id}`}>View profile</Link><Link className="btn btn-primary flex-1" href={`/appointments?doctor=${doctor.id}`}>Book</Link></div></article>}
export function HospitalCard({hospital,emergency=false}:{hospital:Hospital;emergency?:boolean}){return <article className="card p-5"><div className="flex justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="font-extrabold">{hospital.name}</h2>{hospital.verified&&<BadgeCheck size={17} className="text-green-600"/>}</div><p className="muted text-sm mt-1">{hospital.type} · {hospital.location}</p></div><StatusBadge tone={hospital.open?"green":"amber"}>{hospital.open?"Open":"Closed"}</StatusBadge></div><div className="flex flex-wrap gap-2 my-4"><span className="pill bg-slate-100">{hospital.distance}</span><span className="pill bg-slate-100">{hospital.eta} away</span>{hospital.emergency&&<StatusBadge tone="red">24/7 Emergency</StatusBadge>}</div><p className="muted text-sm">{hospital.services.join(" · ")}</p><div className="flex flex-wrap gap-2 mt-5">{emergency&&<button className="btn btn-outline"><Phone size={17}/>Call</button>}{emergency&&<button className="btn btn-outline"><Navigation size={17}/>Navigate</button>}<Link className="btn btn-primary" href={`/hospitals/${hospital.id}`}>View</Link>{emergency&&<Link className="btn btn-outline" href="/messages/unity-emergency">Notify</Link>}</div></article>}
export function PrescriptionCard({item}:{item:Prescription}){return <article className="card p-5 flex justify-between items-center gap-4"><div><StatusBadge>{item.status}</StatusBadge><h2 className="font-extrabold mt-3">Prescription · {item.medicines.length} medicines</h2><p className="muted text-sm">{item.doctor} · {item.date}</p></div><Link href={`/prescriptions/${item.id}`} aria-label="View prescription"><ChevronRight/></Link></article>}
export function EmptyState({title="Nothing here yet",text="New activity will appear here."}:{title?:string;text?:string}){return <div className="card p-10 text-center"><Calendar className="mx-auto text-slate-300" size={38}/><h2 className="font-bold mt-3">{title}</h2><p className="muted text-sm mt-1">{text}</p></div>}
export function LoadingSkeleton(){return <div className="space-y-3 animate-pulse" aria-label="Loading"><div className="h-28 rounded-2xl bg-slate-200"/><div className="h-28 rounded-2xl bg-slate-200"/></div>}
export function SmartCard({title,lines,href}:{title:string;lines:string[];href?:string}){const body=<div className="border-l-4 border-green-500 bg-white rounded-xl p-4 shadow-sm"><p className="font-extrabold">{title}</p>{lines.map(x=><p className="text-sm muted mt-1" key={x}>{x}</p>)}</div>;return href?<Link href={href}>{body}</Link>:body}
export function Meta({date,time}:{date:string;time:string}){return <p className="flex gap-3 muted text-sm"><span className="flex gap-1"><Calendar size={15}/>{date}</span><span className="flex gap-1"><Clock size={15}/>{time}</span></p>}
