import Link from "next/link";
import {ArrowRight,Building2,Check,Circle,Clock3,FileCheck2,ShieldCheck,Stethoscope,UserRound} from "lucide-react";
import type {ApiUser} from "@/lib/api/types";
import {PageHeader,StatusBadge} from "./ui";

type WorkspaceKind="doctor"|"hospital"|"admin";
const content={doctor:{eyebrow:"Doctor workspace",title:"Set up your professional account",description:"Complete your identity and professional information before provider tools are activated.",icon:Stethoscope,steps:["Account created","Professional profile","Licence and identity review","Workspace activation"]},hospital:{eyebrow:"Hospital workspace",title:"Connect your organisation",description:"Organisation authority and facility information must be reviewed before hospital tools are activated.",icon:Building2,steps:["Account created","Organisation information","Authority verification","Workspace activation"]},admin:{eyebrow:"Administration",title:"Platform operations",description:"This private workspace is reserved for provisioned administrator accounts.",icon:ShieldCheck,steps:["Administrator provisioned","Secure access confirmed","Operations access"]}} as const;

export function WorkspaceOverview({user,kind}:{user:ApiUser;kind:WorkspaceKind}){const item=content[kind],Icon=item.icon,active=user.account_status==="active",suspended=user.account_status==="suspended";return <div className="page"><PageHeader title={item.eyebrow} subtitle={`Welcome, ${user.first_name}.`}/><section className="card overflow-hidden"><div className="bg-gradient-to-br from-green-700 to-green-500 p-6 text-white md:p-8"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white/15"><Icon size={25}/></div><h2 className="mt-5 max-w-xl text-2xl font-black md:text-3xl">{item.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-green-50">{item.description}</p></div><div className="grid gap-6 p-6 md:grid-cols-[1.2fr_.8fr] md:p-8"><div><div className="flex items-center justify-between gap-3"><h3 className="font-black">Account progress</h3><StatusBadge tone={suspended?"red":active?"green":"amber"}>{suspended?"Suspended":active?"Active":"Review pending"}</StatusBadge></div><ol className="mt-5 space-y-1">{item.steps.map((step,index)=>{const complete=index===0||active;return <li key={step} className="flex items-center gap-3 rounded-xl px-1 py-3 text-sm"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full ${complete?"bg-green-100 text-green-700":"bg-slate-100 text-slate-400"}`}>{complete?<Check size={15}/>:index===1&&!suspended?<Clock3 size={14}/>:<Circle size={11}/>}</span><span className={complete?"font-bold":"text-slate-500"}>{step}</span></li>})}</ol></div><aside className="rounded-2xl bg-slate-50 p-5"><div className="flex items-center gap-3"><UserRound className="text-green-700" size={21}/><h3 className="font-black">Account details</h3></div><dl className="mt-5 space-y-4 text-sm"><div><dt className="muted">Name</dt><dd className="mt-1 font-bold">{user.first_name} {user.last_name}</dd></div><div><dt className="muted">Email</dt><dd className="mt-1 break-all font-bold">{user.email}</dd></div><div><dt className="muted">Role</dt><dd className="mt-1 font-bold capitalize">{user.role.replace("_"," ")}</dd></div></dl><Link href="/profile" className="btn btn-outline mt-6 w-full">View account <ArrowRight size={16}/></Link></aside></div></section>{!active&&!suspended&&<section className="mt-5 flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-900"><FileCheck2 className="mt-0.5 shrink-0" size={20}/><div><h2 className="font-black">Your account is awaiting verification</h2><p className="mt-1 text-sm leading-6">Provider operations remain unavailable until the required verification workflow is released and your account is approved.</p></div></section>}</div>}
