import Link from "next/link";
import {ArrowRight,Search,SlidersHorizontal} from "lucide-react";
import {DoctorCard,PageHeader} from "@/components/ui";
import {doctorService} from "@/lib/services";
const specialties=["General Physician","Cardiology","Pediatrics","Dermatology","Gynecology","Orthopedics","Mental Health"];
export default async function Doctors({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const query=await searchParams;
 let data:Awaited<ReturnType<typeof doctorService.getAll>>=[];
 let unavailable=false;
 try{data=await doctorService.getAll({search:query.search,specialty:query.specialty,city:query.city,max_fee:query.max_fee,verified_only:query.verified_only==="true"})}catch{unavailable=true}
 function specialtyHref(specialty:string){const params=new URLSearchParams();for(const key of ["search","city","max_fee","verified_only"])if(query[key])params.set(key,query[key]!);if(specialty)params.set("specialty",specialty);return "/doctors?"+params.toString()}
 return <div className="page"><PageHeader title="Find your kind of care." subtitle="Search by specialty, location, and budget. Find a doctor who fits your next step."/>
 <form className="card doctor-filters" action="/doctors" role="search"><div className="filter-fields"><label>Doctor or specialty<input name="search" defaultValue={query.search} className="field" placeholder="Name or specialty"/></label><label>Location<input name="city" defaultValue={query.city} className="field" placeholder="e.g. Awka"/></label><label>Budget (₦)<input name="max_fee" defaultValue={query.max_fee} className="field" type="number" min="0" placeholder="Maximum fee"/></label><button className="btn btn-primary"><Search size={17}/>Search</button></div>{query.specialty&&<input type="hidden" name="specialty" value={query.specialty}/>}<div className="flex flex-wrap items-center justify-between gap-3 mt-4"><label className="flex min-h-10 items-center gap-2 text-xs"><input type="checkbox" name="verified_only" value="true" defaultChecked={query.verified_only==="true"} className="accent-green-700"/>Verified profiles only</label><Link href="/doctors" className="text-xs font-bold text-green-700 py-2">Reset filters</Link></div></form>
 <nav className="specialty-list" aria-label="Filter by specialty">{["",...specialties].map(specialty=><Link href={specialtyHref(specialty)} key={specialty} aria-current={(query.specialty||"")===specialty?"true":undefined} className={"pill "+((query.specialty||"")===specialty?"bg-green-700 text-white":"bg-white border border-slate-200")}>{specialty||"All specialties"}</Link>)}</nav>
 {unavailable?<section className="card p-8"><Search className="text-green-700" size={30}/><h2 className="font-bold text-lg mt-4">The directory is taking a moment.</h2><p className="muted text-sm mt-2">We couldn’t connect to the doctor directory. Please try again shortly.</p><Link href={specialtyHref(query.specialty||"")} className="btn btn-primary mt-5">Try again <ArrowRight size={16}/></Link></section>:<><div className="results-heading"><span>{data.length} {data.length===1?"doctor":"doctors"} shown</span><span className="flex items-center gap-2"><SlidersHorizontal size={14}/>Matched to your filters</span></div><div className="grid lg:grid-cols-2 gap-4">{data.map(doctor=><DoctorCard doctor={doctor} key={doctor.id}/>)}</div>{data.length===0&&<section className="card p-8 text-center"><h2 className="font-bold text-lg">Let’s widen the search.</h2><p className="muted text-sm mt-2">Try a different city, a higher budget, or another specialty.</p><Link href="/doctors" className="btn btn-outline mt-5">Clear filters</Link></section>}</>}
 <p className="demo-note">Demo directory · All practitioner profiles are fictional. Verification badges describe demonstration records.</p></div>;
}
